import json
from textwrap import dedent

kitsune_data = [
    {"id": "kitsune-001", "theme": "lenda", "title": "Tamamo-no-Mae e o Imperador Konoe", "summary": "A cortesa Tamamo-no-Mae encantou a corte Heian ate ser revelada como kitsune de nove caudas.", "moral": "Orgulho desmedido pode derrubar ate o mais poderoso.", "story": "No seculo XII, Tamamo-no-Mae servia ao imperador Konoe exibindo beleza e erudicao incomparaveis. Onmyoji Abe no Yasuchika realizou ritual e descobriu que a dama era uma kitsune de nove caudas alimentando a doenca do soberano. A raposa fugiu para Nasu, foi abatida por guerreiros e seu corpo virou a rocha Sessho-seki, cuja fama de matar quem a tocasse perdura no folclore.", "keywords": ["tamamo-no-mae", "konoe", "sessho-seki", "kitsune"]},
    {"id": "kitsune-002", "theme": "familia", "title": "Kuzunoha, a Mae Raposa", "summary": "Kuzunoha salvou Abe no Yasuna e criou Abe no Seimei antes de regressar a floresta de Shinoda.", "moral": "Lacos verdadeiros resistem mesmo entre mundos diferentes.", "story": "A raposa Kuzunoha resgatou o guerreiro Abe no Yasuna de cacadores, tomou forma humana e com ele teve um filho: Abe no Seimei, futuro mestre da magia onmyo. Quando a verdadeira identidade foi descoberta, Kuzunoha voltou a Shinoda, mas deixou bilhete indicando a familia a visitar o santuario que ate hoje recebe devotos agradecidos.", "keywords": ["kuzunoha", "shinoda", "abe-no-seimei", "kitsune"]},
    {"id": "kitsune-003", "theme": "casamento", "title": "Casamento de Raposas em Echigo", "summary": "Moradores de Niigata descrevem cortejo luminoso cruzando campos como casamento de kitsune.", "moral": "Fenomenos naturais inspiram respeito aos espiritos da paisagem.", "story": "Relatos do periodo Edo mencionam colunas de luz deslocando-se sobre arrozais enevoados em Echigo. As familias interpretaram o brilho como kitsune celebrando casamento e passaram a deixar oferendas para Inari em noites umidas. Hoje, o festival Kitsune no Yomeiri reencena o cortejo com lanternas e mascaras.", "keywords": ["echigo", "festival", "kitsune", "inari"]},
    {"id": "kitsune-004", "theme": "gratidao", "title": "Raposa de Toyokawa Inari", "summary": "Agricultores da provincia de Mikawa agradeceram a raposa sagrada por devolver irrigacao aos campos.", "moral": "Gratidao fertiliza esperanca e colheitas.", "story": "Durante uma seca, o monge Tokai Gyoei difundiu o culto de Toyokawa Inari. Depois de visoes com raposa mensageira, os agricultores escavaram canais conforme orientado no sonho. A chuva chegou e a colheita se recuperou, originando o grande santuario de Toyokawa, referencia para comerciantes e artistas ate hoje.", "keywords": ["toyokawa", "mikawa", "inari", "colheita"]},
    {"id": "kitsune-005", "theme": "bondade", "title": "O Lenhador Yoshizawa", "summary": "Yoshizawa libertou uma raposa e recebeu arroz misterioso durante uma fome em Akita.", "moral": "Bons gestos voltam em momentos de necessidade.", "story": "Registros locais contam que Yoshizawa encontrou uma raposa presa e a libertou. Meses depois, sacos de arroz apareceram em sua porta quando a aldeia sofria escassez. Ao longe, ele viu uma raposa observar e partir. O evento virou lenda recitada em festivais do norte do Japao.", "keywords": ["akita", "gratidao", "lenhador", "kitsune"]},
    {"id": "kitsune-006", "theme": "celebracao", "title": "Processao de Oji", "summary": "Tokyo celebra todos os anos a suposta reuniao de raposas na virada do ano.", "moral": "Rituais fortalecem memoria de comunidade e espiritos guardioes.", "story": "Cronistas de Edo relatavam que kitsune se reuniam sob um grande pinheiro em Oji antes de visitar santuarios de Inari na passagem do ano. Moradores modernos transformaram a historia em desfile de lanternas e mascaras, o Oji Kitsune no Gyoretsu, reforcando identidade do bairro.", "keywords": ["oji", "tokyo", "festival", "kitsune"]},
    {"id": "kitsune-007", "theme": "chuva", "title": "Raposa de Izumo", "summary": "Santuarios de Izumo descrevem raposa pedindo aos ventos que regassem plantacoes.", "moral": "Natureza responde quando humanos escutam com humildade.", "story": "Cronicas paroquiais relatam que um sacerdote de Izumo implorou pela chuva na presenca de uma raposa mensageira. Logo apareceram nuvens vindas do Mar do Japao, salvando plantacoes. O episodio alimentou peregrinacoes ao santuario Hinomisaki.", "keywords": ["izumo", "chuva", "inari", "agricultura"]},
    {"id": "kitsune-008", "theme": "arte", "title": "Kitsune do Taiko de Nagano", "summary": "Jovens bateristas contam que uma raposa os presenteou com novos ritmos.", "moral": "Compartilhar arte constroi harmonia.", "story": "Durante preparativos de festival em Nagano, um jovem percebeu cauda surgir atras de colega talentosa. Ao ser reconhecida, a raposa prometeu proteger a aldeia e desapareceu, deixando ritmos que ainda hoje caracterizam o taiko da regiao.", "keywords": ["nagano", "taiko", "festival", "kitsune"]},
    {"id": "kitsune-009", "theme": "amizade", "title": "Sentaro e a Raposa Estrategista", "summary": "Legenda militar cita uma raposa que ensinou taticas para evitar banho de sangue.", "moral": "Sabedoria inclui escolher a paz quando possivel.", "story": "Narrativas de Mino descrevem o samurai Sentaro ajudando raposa ferida. Ela retornou em sonhos, sugerindo manobras que evitaram batalha prolongada. Gratidao levou Sentaro a erguer altar para Inari e adotar postura diplomatica.", "keywords": ["mino", "samurai", "diplomacia", "kitsune"]},
    {"id": "kitsune-010", "theme": "festival", "title": "Tochas de Shinoda", "summary": "Visitantes relatam colunas de fogo rumo ao templo de Kuzunoha em Osaka.", "moral": "Luzes noturnas mantem viva a memoria dos espiritos.", "story": "Durante o festival Setsubun, moradores de Osaka dizem ver pontos luminosos que lembram raposas carregando tochas ate o templo Shinoda. O cortejo simboliza a raposa Kuzunoha guiando fieis e protege a cidade contra epidemias, segundo crenças locais.", "keywords": ["shinoda", "osaka", "setsubun", "kitsune"]}
]

json_output = json.dumps(kitsune_data, ensure_ascii=True, indent=2)

print(json_output[:200])
