export interface Story {
  id: string
  theme: string
  title: string
  summary: string
  moral: string
  story: string
  keywords: string[]
}

export const bakenekoStories: Story[] = [
  {
    id: "bakeneko-001",
    theme: "hospital",
    title: "File of Residual Static",
    summary: "A bakeneko invites mortals to test a boundary they should respect.",
    moral: "Fear thrives when arrogance silences warnings.",
    story: "In the shuttered hospital wing, a bakeneko named Kuro prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that those who ignore the omen wake up marked with charcoal paw prints. Since the tale spread, now commuters hang cat charms on emergency cords.",
    keywords: ["hospital", "wing", "file", "bakeneko"],
  },
  {
    id: "bakeneko-002",
    theme: "maldicao",
    title: "Room of the Flooded Ward",
    summary: "A haunted site trades sanctuary for uncomfortable truth.",
    moral: "Curses bloom wherever pride refuses to kneel.",
    story: "In an empty theme park, a bakeneko named Saya prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that the guilty hear their secrets counted each midnight. Since the tale spread, Caretakers chalk paw prints near the fuse box.",
    keywords: ["maldicao", "park", "room", "bakeneko"],
  },
  {
    id: "bakeneko-003",
    theme: "fantasma",
    title: "Whisper of the Third Shift",
    summary: "A rumor grows teeth when ignored by those in power.",
    moral: "Every forgotten victim eventually drafts their own rescue.",
    story: "In the coal furnace tunnels, a bakeneko named Gin prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that any patient file removed grows teeth and returns. Since the tale spread, Graffiti artists sketch twin tails on every exit sign.",
    keywords: ["fantasma", "tunnels", "whisper", "bakeneko"],
  },
  {
    id: "bakeneko-004",
    theme: "vinganca",
    title: "Ward of the Returned Gaze",
    summary: "A caretaker learns why apologies are more precious than locks.",
    moral: "The dead wait patiently for a listening ear.",
    story: "In a clockwork museum, a bakeneko named Ame prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that any who run are chased by echoes wearing their shoes. Since the tale spread, Paramedics leave bowls of cream by the loading bay.",
    keywords: ["vinganca", "museum", "ward", "bakeneko"],
  },
  {
    id: "bakeneko-005",
    theme: "pesadelo",
    title: "Wing of the Endless Intake",
    summary: "A traveling skeptic discovers that curiosity feeds the dark.",
    moral: "Justice from the shadows collects double interest.",
    story: "In the locked records vault, a bakeneko named Roku prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that visitors who mock the place lose their shadow. Since the tale spread, Visitors count every window twice before leaving.",
    keywords: ["pesadelo", "vault", "wing", "bakeneko"],
  },
  {
    id: "bakeneko-006",
    theme: "yokai",
    title: "Ledger of Lamented Check Out",
    summary: "A family secret crawls back through abandoned corridors.",
    moral: "Those who barter with grief must carry the change.",
    story: "In a derelict observatory, a bakeneko named Yoru prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that trespassers become silhouettes on the wall until dawn. Since the tale spread, Security guards wear bells hidden inside sleeves.",
    keywords: ["yokai", "observatory", "ledger", "bakeneko"],
  },
  {
    id: "bakeneko-007",
    theme: "memoria",
    title: "Night of Needle Weather",
    summary: "A midnight crew bargains with a cat that remembers debts.",
    moral: "Silence can shield or strangle depending on who holds it.",
    story: "In the storm-buried library, a bakeneko named Mado prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that resigned victims find ticket stubs stapled to their skin. Since the tale spread, Nurses whisper headcounts before passing doorways.",
    keywords: ["memoria", "library", "night", "bakeneko"],
  },
  {
    id: "bakeneko-008",
    theme: "obsessao",
    title: "Case of Mewling Silence",
    summary: "A ritual promises safety but demands payment in whispers.",
    moral: "Secrets rot faster than wounds.",
    story: "In a sunken freight dock, a bakeneko named Chika prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that anyone who speaks too loudly bites their tongue until it bleeds. Since the tale spread, Locals warn newcomers to applaud the unseen performer.",
    keywords: ["obsessao", "dock", "case", "bakeneko"],
  },
  {
    id: "bakeneko-009",
    theme: "ritual",
    title: "Altar of Lurking Consent",
    summary: "A collector of evidence meets the source of the stains.",
    moral: "Nightmares feast on promises never honored.",
    story: "In the plague quarantine garden, a bakeneko named Hibi prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that stubborn listeners find their reflections refusing to return. Since the tale spread, Night shift workers trade matches etched with whiskers.",
    keywords: ["ritual", "garden", "altar", "bakeneko"],
  },
  {
    id: "bakeneko-010",
    theme: "esquecimento",
    title: "Mask of the Velvet Sutra",
    summary: "A local guide breaks the rules and pays in memories.",
    moral: "Curiosity without compassion sharpens the claws of the dark.",
    story: "In a forgotten coastal fortress, a bakeneko named Nami prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that flashlights fail within three breaths of arrogance. Since the tale spread, Children dare each other to knock only once.",
    keywords: ["esquecimento", "fortress", "mask", "bakeneko"],
  },
  {
    id: "bakeneko-011",
    theme: "hospital",
    title: "Mirror of Sixteenth Bell",
    summary: "A bakeneko invites mortals to test a boundary they should respect.",
    moral: "Fear thrives when arrogance silences warnings.",
    story: "In the paper lantern warehouse, a bakeneko named Kage prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that the emergency exit counts down names instead of seconds. Since the tale spread, now commuters hang cat charms on emergency cords.",
    keywords: ["hospital", "warehouse", "mirror", "bakeneko"],
  },
  {
    id: "bakeneko-012",
    theme: "maldicao",
    title: "Signal of the Hollow Surgeon",
    summary: "A haunted site trades sanctuary for uncomfortable truth.",
    moral: "Curses bloom wherever pride refuses to kneel.",
    story: "In an echoing radio tower, a bakeneko named En prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that apprentice exorcists must replace a bulb with their own memory. Since the tale spread, Caretakers chalk paw prints near the fuse box.",
    keywords: ["maldicao", "tower", "signal", "bakeneko"],
  },
  {
    id: "bakeneko-013",
    theme: "fantasma",
    title: "Suture of the Paper Scalpel",
    summary: "A rumor grows teeth when ignored by those in power.",
    moral: "Every forgotten victim eventually drafts their own rescue.",
    story: "In the rusted aquarium, a bakeneko named Toki prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that living guests sneeze out saltwater moss for a week. Since the tale spread, Graffiti artists sketch twin tails on every exit sign.",
    keywords: ["fantasma", "aquarium", "suture", "bakeneko"],
  },
  {
    id: "bakeneko-014",
    theme: "vinganca",
    title: "Threshold of the Bone Lantern",
    summary: "A caretaker learns why apologies are more precious than locks.",
    moral: "The dead wait patiently for a listening ear.",
    story: "In an abandoned bathhouse, a bakeneko named Sumi prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that running water speaks in the voice of the last person ignored. Since the tale spread, Paramedics leave bowls of cream by the loading bay.",
    keywords: ["vinganca", "bathhouse", "threshold", "bakeneko"],
  },
  {
    id: "bakeneko-015",
    theme: "pesadelo",
    title: "Vial of the Phantom Siren",
    summary: "A traveling skeptic discovers that curiosity feeds the dark.",
    moral: "Justice from the shadows collects double interest.",
    story: "In the silent bell factory, a bakeneko named Rai prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that visitors leave with pockets full of rust they never collected. Since the tale spread, Visitors count every window twice before leaving.",
    keywords: ["pesadelo", "factory", "vial", "bakeneko"],
  },
  {
    id: "bakeneko-016",
    theme: "yokai",
    title: "Catwalk of Forgotten Vespers",
    summary: "A family secret crawls back through abandoned corridors.",
    moral: "Those who barter with grief must carry the change.",
    story: "In a collapsed textile mill, a bakeneko named Kiri prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that every skeptic discovers a voice sealed inside their throat. Since the tale spread, Security guards wear bells hidden inside sleeves.",
    keywords: ["yokai", "mill", "catwalk", "bakeneko"],
  },
  {
    id: "bakeneko-017",
    theme: "memoria",
    title: "Bargain of the Withered Nurse",
    summary: "A midnight crew bargains with a cat that remembers debts.",
    moral: "Silence can shield or strangle depending on who holds it.",
    story: "In the night market basement, a bakeneko named Tsuru prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that apologies are the only currency accepted by the doors. Since the tale spread, Nurses whisper headcounts before passing doorways.",
    keywords: ["memoria", "basement", "bargain", "bakeneko"],
  },
  {
    id: "bakeneko-018",
    theme: "obsessao",
    title: "Pulse of Catcalled Promises",
    summary: "A ritual promises safety but demands payment in whispers.",
    moral: "Secrets rot faster than wounds.",
    story: "In an uprooted shrine, a bakeneko named Mizu prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that stair rails pulse like arteries around liars. Since the tale spread, Locals warn newcomers to applaud the unseen performer.",
    keywords: ["obsessao", "shrine", "pulse", "bakeneko"],
  },
  {
    id: "bakeneko-019",
    theme: "ritual",
    title: "Siren of the Static Choir",
    summary: "A collector of evidence meets the source of the stains.",
    moral: "Nightmares feast on promises never honored.",
    story: "In the provincial archive, a bakeneko named Neru prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that every question adds a crack to the nearest bone jar. Since the tale spread, Night shift workers trade matches etched with whiskers.",
    keywords: ["ritual", "archive", "siren", "bakeneko"],
  },
  {
    id: "bakeneko-020",
    theme: "esquecimento",
    title: "Curtain of the Feral Chart",
    summary: "A local guide breaks the rules and pays in memories.",
    moral: "Curiosity without compassion sharpens the claws of the dark.",
    story: "In an underground theater, a bakeneko named Shiba prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that anyone who films the haunt records only their own confession. Since the tale spread, Children dare each other to knock only once.",
    keywords: ["esquecimento", "theater", "curtain", "bakeneko"],
  },
  {
    id: "bakeneko-021",
    theme: "hospital",
    title: "File of Residual Static",
    summary: "A bakeneko invites mortals to test a boundary they should respect.",
    moral: "Fear thrives when arrogance silences warnings.",
    story: "In the back alley morgue, a bakeneko named Tohru prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that those who ignore the omen wake up marked with charcoal paw prints. Since the tale spread, now commuters hang cat charms on emergency cords.",
    keywords: ["hospital", "morgue", "file", "bakeneko"],
  },
  {
    id: "bakeneko-022",
    theme: "maldicao",
    title: "Room of the Flooded Ward",
    summary: "A haunted site trades sanctuary for uncomfortable truth.",
    moral: "Curses bloom wherever pride refuses to kneel.",
    story: "In a drowned bell road, a bakeneko named Kuzu prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that the guilty hear their secrets counted each midnight. Since the tale spread, Caretakers chalk paw prints near the fuse box.",
    keywords: ["maldicao", "road", "room", "bakeneko"],
  },
  {
    id: "bakeneko-023",
    theme: "fantasma",
    title: "Whisper of the Third Shift",
    summary: "A rumor grows teeth when ignored by those in power.",
    moral: "Every forgotten victim eventually drafts their own rescue.",
    story: "In the forest crematorium, a bakeneko named Kane prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that any patient file removed grows teeth and returns. Since the tale spread, Graffiti artists sketch twin tails on every exit sign.",
    keywords: ["fantasma", "crematorium", "whisper", "bakeneko"],
  },
  {
    id: "bakeneko-024",
    theme: "vinganca",
    title: "Ward of the Returned Gaze",
    summary: "A caretaker learns why apologies are more precious than locks.",
    moral: "The dead wait patiently for a listening ear.",
    story: "In a decommissioned lighthouse, a bakeneko named Azra prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that any who run are chased by echoes wearing their shoes. Since the tale spread, Paramedics leave bowls of cream by the loading bay.",
    keywords: ["vinganca", "lighthouse", "ward", "bakeneko"],
  },
  {
    id: "bakeneko-025",
    theme: "pesadelo",
    title: "Wing of the Endless Intake",
    summary: "A traveling skeptic discovers that curiosity feeds the dark.",
    moral: "Justice from the shadows collects double interest.",
    story: "In the midnight cable car, a bakeneko named Ino prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that visitors who mock the place lose their shadow. Since the tale spread, Visitors count every window twice before leaving.",
    keywords: ["pesadelo", "car", "wing", "bakeneko"],
  },
  {
    id: "bakeneko-026",
    theme: "yokai",
    title: "Ledger of Lamented Check Out",
    summary: "A family secret crawls back through abandoned corridors.",
    moral: "Those who barter with grief must carry the change.",
    story: "In a sealed train carriage, a bakeneko named Kori prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that trespassers become silhouettes on the wall until dawn. Since the tale spread, Security guards wear bells hidden inside sleeves.",
    keywords: ["yokai", "carriage", "ledger", "bakeneko"],
  },
  {
    id: "bakeneko-027",
    theme: "memoria",
    title: "Night of Needle Weather",
    summary: "A midnight crew bargains with a cat that remembers debts.",
    moral: "Silence can shield or strangle depending on who holds it.",
    story: "In the flooded subway station, a bakeneko named Jiro prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that resigned victims find ticket stubs stapled to their skin. Since the tale spread, Nurses whisper headcounts before passing doorways.",
    keywords: ["memoria", "station", "night", "bakeneko"],
  },
  {
    id: "bakeneko-028",
    theme: "obsessao",
    title: "Case of Mewling Silence",
    summary: "A ritual promises safety but demands payment in whispers.",
    moral: "Secrets rot faster than wounds.",
    story: "In a snowbound clinic, a bakeneko named Mika prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that anyone who speaks too loudly bites their tongue until it bleeds. Since the tale spread, Locals warn newcomers to applaud the unseen performer.",
    keywords: ["obsessao", "clinic", "case", "bakeneko"],
  },
  {
    id: "bakeneko-029",
    theme: "ritual",
    title: "Altar of Lurking Consent",
    summary: "A collector of evidence meets the source of the stains.",
    moral: "Nightmares feast on promises never honored.",
    story: "In the mirror lined dormitory, a bakeneko named Nagi prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that stubborn listeners find their reflections refusing to return. Since the tale spread, Night shift workers trade matches etched with whiskers.",
    keywords: ["ritual", "dormitory", "altar", "bakeneko"],
  },
  {
    id: "bakeneko-030",
    theme: "esquecimento",
    title: "Mask of the Velvet Sutra",
    summary: "A local guide breaks the rules and pays in memories.",
    moral: "Curiosity without compassion sharpens the claws of the dark.",
    story: "In an illegal surgery den, a bakeneko named Oba prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that flashlights fail within three breaths of arrogance. Since the tale spread, Children dare each other to knock only once.",
    keywords: ["esquecimento", "den", "mask", "bakeneko"],
  },
  {
    id: "bakeneko-031",
    theme: "hospital",
    title: "Mirror of Sixteenth Bell",
    summary: "A bakeneko invites mortals to test a boundary they should respect.",
    moral: "Fear thrives when arrogance silences warnings.",
    story: "In the shuttered hospital wing, a bakeneko named Retsu prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that the emergency exit counts down names instead of seconds. Since the tale spread, now commuters hang cat charms on emergency cords.",
    keywords: ["hospital", "wing", "mirror", "bakeneko"],
  },
  {
    id: "bakeneko-032",
    theme: "maldicao",
    title: "Signal of the Hollow Surgeon",
    summary: "A haunted site trades sanctuary for uncomfortable truth.",
    moral: "Curses bloom wherever pride refuses to kneel.",
    story: "In an empty theme park, a bakeneko named Sora prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that apprentice exorcists must replace a bulb with their own memory. Since the tale spread, Caretakers chalk paw prints near the fuse box.",
    keywords: ["maldicao", "park", "signal", "bakeneko"],
  },
  {
    id: "bakeneko-033",
    theme: "fantasma",
    title: "Suture of the Paper Scalpel",
    summary: "A rumor grows teeth when ignored by those in power.",
    moral: "Every forgotten victim eventually drafts their own rescue.",
    story: "In the coal furnace tunnels, a bakeneko named Tara prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that living guests sneeze out saltwater moss for a week. Since the tale spread, Graffiti artists sketch twin tails on every exit sign.",
    keywords: ["fantasma", "tunnels", "suture", "bakeneko"],
  },
  {
    id: "bakeneko-034",
    theme: "vinganca",
    title: "Threshold of the Bone Lantern",
    summary: "A caretaker learns why apologies are more precious than locks.",
    moral: "The dead wait patiently for a listening ear.",
    story: "In a clockwork museum, a bakeneko named Une prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that running water speaks in the voice of the last person ignored. Since the tale spread, Paramedics leave bowls of cream by the loading bay.",
    keywords: ["vinganca", "museum", "threshold", "bakeneko"],
  },
  {
    id: "bakeneko-035",
    theme: "pesadelo",
    title: "Vial of the Phantom Siren",
    summary: "A traveling skeptic discovers that curiosity feeds the dark.",
    moral: "Justice from the shadows collects double interest.",
    story: "In the locked records vault, a bakeneko named Yura prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that visitors leave with pockets full of rust they never collected. Since the tale spread, Visitors count every window twice before leaving.",
    keywords: ["pesadelo", "vault", "vial", "bakeneko"],
  },
  {
    id: "bakeneko-036",
    theme: "yokai",
    title: "Catwalk of Forgotten Vespers",
    summary: "A family secret crawls back through abandoned corridors.",
    moral: "Those who barter with grief must carry the change.",
    story: "In a derelict observatory, a bakeneko named Zei prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that every skeptic discovers a voice sealed inside their throat. Since the tale spread, Security guards wear bells hidden inside sleeves.",
    keywords: ["yokai", "observatory", "catwalk", "bakeneko"],
  },
  {
    id: "bakeneko-037",
    theme: "memoria",
    title: "Bargain of the Withered Nurse",
    summary: "A midnight crew bargains with a cat that remembers debts.",
    moral: "Silence can shield or strangle depending on who holds it.",
    story: "In the storm-buried library, a bakeneko named Haku prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that apologies are the only currency accepted by the doors. Since the tale spread, Nurses whisper headcounts before passing doorways.",
    keywords: ["memoria", "library", "bargain", "bakeneko"],
  },
  {
    id: "bakeneko-038",
    theme: "obsessao",
    title: "Pulse of Catcalled Promises",
    summary: "A ritual promises safety but demands payment in whispers.",
    moral: "Secrets rot faster than wounds.",
    story: "In a sunken freight dock, a bakeneko named Ire prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that stair rails pulse like arteries around liars. Since the tale spread, Locals warn newcomers to applaud the unseen performer.",
    keywords: ["obsessao", "dock", "pulse", "bakeneko"],
  },
  {
    id: "bakeneko-039",
    theme: "ritual",
    title: "Siren of the Static Choir",
    summary: "A collector of evidence meets the source of the stains.",
    moral: "Nightmares feast on promises never honored.",
    story: "In the plague quarantine garden, a bakeneko named Kama prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that every question adds a crack to the nearest bone jar. Since the tale spread, Night shift workers trade matches etched with whiskers.",
    keywords: ["ritual", "garden", "siren", "bakeneko"],
  },
  {
    id: "bakeneko-040",
    theme: "esquecimento",
    title: "Curtain of the Feral Chart",
    summary: "A local guide breaks the rules and pays in memories.",
    moral: "Curiosity without compassion sharpens the claws of the dark.",
    story: "In a forgotten coastal fortress, a bakeneko named Lune prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that anyone who films the haunt records only their own confession. Since the tale spread, Children dare each other to knock only once.",
    keywords: ["esquecimento", "fortress", "curtain", "bakeneko"],
  },
  {
    id: "bakeneko-041",
    theme: "hospital",
    title: "File of Residual Static",
    summary: "A bakeneko invites mortals to test a boundary they should respect.",
    moral: "Fear thrives when arrogance silences warnings.",
    story: "In the paper lantern warehouse, a bakeneko named Mara prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that those who ignore the omen wake up marked with charcoal paw prints. Since the tale spread, now commuters hang cat charms on emergency cords.",
    keywords: ["hospital", "warehouse", "file", "bakeneko"],
  },
  {
    id: "bakeneko-042",
    theme: "maldicao",
    title: "Room of the Flooded Ward",
    summary: "A haunted site trades sanctuary for uncomfortable truth.",
    moral: "Curses bloom wherever pride refuses to kneel.",
    story: "In an echoing radio tower, a bakeneko named Nao prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that the guilty hear their secrets counted each midnight. Since the tale spread, Caretakers chalk paw prints near the fuse box.",
    keywords: ["maldicao", "tower", "room", "bakeneko"],
  },
  {
    id: "bakeneko-043",
    theme: "fantasma",
    title: "Whisper of the Third Shift",
    summary: "A rumor grows teeth when ignored by those in power.",
    moral: "Every forgotten victim eventually drafts their own rescue.",
    story: "In the rusted aquarium, a bakeneko named Ori prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that any patient file removed grows teeth and returns. Since the tale spread, Graffiti artists sketch twin tails on every exit sign.",
    keywords: ["fantasma", "aquarium", "whisper", "bakeneko"],
  },
  {
    id: "bakeneko-044",
    theme: "vinganca",
    title: "Ward of the Returned Gaze",
    summary: "A caretaker learns why apologies are more precious than locks.",
    moral: "The dead wait patiently for a listening ear.",
    story: "In an abandoned bathhouse, a bakeneko named Peko prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that any who run are chased by echoes wearing their shoes. Since the tale spread, Paramedics leave bowls of cream by the loading bay.",
    keywords: ["vinganca", "bathhouse", "ward", "bakeneko"],
  },
  {
    id: "bakeneko-045",
    theme: "pesadelo",
    title: "Wing of the Endless Intake",
    summary: "A traveling skeptic discovers that curiosity feeds the dark.",
    moral: "Justice from the shadows collects double interest.",
    story: "In the silent bell factory, a bakeneko named Quen prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that visitors who mock the place lose their shadow. Since the tale spread, Visitors count every window twice before leaving.",
    keywords: ["pesadelo", "factory", "wing", "bakeneko"],
  },
  {
    id: "bakeneko-046",
    theme: "yokai",
    title: "Ledger of Lamented Check Out",
    summary: "A family secret crawls back through abandoned corridors.",
    moral: "Those who barter with grief must carry the change.",
    story: "In a collapsed textile mill, a bakeneko named Risa prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that trespassers become silhouettes on the wall until dawn. Since the tale spread, Security guards wear bells hidden inside sleeves.",
    keywords: ["yokai", "mill", "ledger", "bakeneko"],
  },
  {
    id: "bakeneko-047",
    theme: "memoria",
    title: "Night of Needle Weather",
    summary: "A midnight crew bargains with a cat that remembers debts.",
    moral: "Silence can shield or strangle depending on who holds it.",
    story: "In the night market basement, a bakeneko named Sei prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that resigned victims find ticket stubs stapled to their skin. Since the tale spread, Nurses whisper headcounts before passing doorways.",
    keywords: ["memoria", "basement", "night", "bakeneko"],
  },
  {
    id: "bakeneko-048",
    theme: "obsessao",
    title: "Case of Mewling Silence",
    summary: "A ritual promises safety but demands payment in whispers.",
    moral: "Secrets rot faster than wounds.",
    story: "In an uprooted shrine, a bakeneko named Tama prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that anyone who speaks too loudly bites their tongue until it bleeds. Since the tale spread, Locals warn newcomers to applaud the unseen performer.",
    keywords: ["obsessao", "shrine", "case", "bakeneko"],
  },
  {
    id: "bakeneko-049",
    theme: "ritual",
    title: "Altar of Lurking Consent",
    summary: "A collector of evidence meets the source of the stains.",
    moral: "Nightmares feast on promises never honored.",
    story: "In the provincial archive, a bakeneko named Ume prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that stubborn listeners find their reflections refusing to return. Since the tale spread, Night shift workers trade matches etched with whiskers.",
    keywords: ["ritual", "archive", "altar", "bakeneko"],
  },
  {
    id: "bakeneko-050",
    theme: "esquecimento",
    title: "Mask of the Velvet Sutra",
    summary: "A local guide breaks the rules and pays in memories.",
    moral: "Curiosity without compassion sharpens the claws of the dark.",
    story: "In an underground theater, a bakeneko named Vei prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that flashlights fail within three breaths of arrogance. Since the tale spread, Children dare each other to knock only once.",
    keywords: ["esquecimento", "theater", "mask", "bakeneko"],
  },
  {
    id: "bakeneko-051",
    theme: "hospital",
    title: "Mirror of Sixteenth Bell",
    summary: "A bakeneko invites mortals to test a boundary they should respect.",
    moral: "Fear thrives when arrogance silences warnings.",
    story: "In the back alley morgue, a bakeneko named Wata prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that the emergency exit counts down names instead of seconds. Since the tale spread, now commuters hang cat charms on emergency cords.",
    keywords: ["hospital", "morgue", "mirror", "bakeneko"],
  },
  {
    id: "bakeneko-052",
    theme: "maldicao",
    title: "Signal of the Hollow Surgeon",
    summary: "A haunted site trades sanctuary for uncomfortable truth.",
    moral: "Curses bloom wherever pride refuses to kneel.",
    story: "In a drowned bell road, a bakeneko named Kuro prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that apprentice exorcists must replace a bulb with their own memory. Since the tale spread, Caretakers chalk paw prints near the fuse box.",
    keywords: ["maldicao", "road", "signal", "bakeneko"],
  },
  {
    id: "bakeneko-053",
    theme: "fantasma",
    title: "Suture of the Paper Scalpel",
    summary: "A rumor grows teeth when ignored by those in power.",
    moral: "Every forgotten victim eventually drafts their own rescue.",
    story: "In the forest crematorium, a bakeneko named Saya prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that living guests sneeze out saltwater moss for a week. Since the tale spread, Graffiti artists sketch twin tails on every exit sign.",
    keywords: ["fantasma", "crematorium", "suture", "bakeneko"],
  },
  {
    id: "bakeneko-054",
    theme: "vinganca",
    title: "Threshold of the Bone Lantern",
    summary: "A caretaker learns why apologies are more precious than locks.",
    moral: "The dead wait patiently for a listening ear.",
    story: "In a decommissioned lighthouse, a bakeneko named Gin prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that running water speaks in the voice of the last person ignored. Since the tale spread, Paramedics leave bowls of cream by the loading bay.",
    keywords: ["vinganca", "lighthouse", "threshold", "bakeneko"],
  },
  {
    id: "bakeneko-055",
    theme: "pesadelo",
    title: "Vial of the Phantom Siren",
    summary: "A traveling skeptic discovers that curiosity feeds the dark.",
    moral: "Justice from the shadows collects double interest.",
    story: "In the midnight cable car, a bakeneko named Ame prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that visitors leave with pockets full of rust they never collected. Since the tale spread, Visitors count every window twice before leaving.",
    keywords: ["pesadelo", "car", "vial", "bakeneko"],
  },
  {
    id: "bakeneko-056",
    theme: "yokai",
    title: "Catwalk of Forgotten Vespers",
    summary: "A family secret crawls back through abandoned corridors.",
    moral: "Those who barter with grief must carry the change.",
    story: "In a sealed train carriage, a bakeneko named Roku prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that every skeptic discovers a voice sealed inside their throat. Since the tale spread, Security guards wear bells hidden inside sleeves.",
    keywords: ["yokai", "carriage", "catwalk", "bakeneko"],
  },
  {
    id: "bakeneko-057",
    theme: "memoria",
    title: "Bargain of the Withered Nurse",
    summary: "A midnight crew bargains with a cat that remembers debts.",
    moral: "Silence can shield or strangle depending on who holds it.",
    story: "In the flooded subway station, a bakeneko named Yoru prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that apologies are the only currency accepted by the doors. Since the tale spread, Nurses whisper headcounts before passing doorways.",
    keywords: ["memoria", "station", "bargain", "bakeneko"],
  },
  {
    id: "bakeneko-058",
    theme: "obsessao",
    title: "Pulse of Catcalled Promises",
    summary: "A ritual promises safety but demands payment in whispers.",
    moral: "Secrets rot faster than wounds.",
    story: "In a snowbound clinic, a bakeneko named Mado prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that stair rails pulse like arteries around liars. Since the tale spread, Locals warn newcomers to applaud the unseen performer.",
    keywords: ["obsessao", "clinic", "pulse", "bakeneko"],
  },
  {
    id: "bakeneko-059",
    theme: "ritual",
    title: "Siren of the Static Choir",
    summary: "A collector of evidence meets the source of the stains.",
    moral: "Nightmares feast on promises never honored.",
    story: "In the mirror lined dormitory, a bakeneko named Chika prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that every question adds a crack to the nearest bone jar. Since the tale spread, Night shift workers trade matches etched with whiskers.",
    keywords: ["ritual", "dormitory", "siren", "bakeneko"],
  },
  {
    id: "bakeneko-060",
    theme: "esquecimento",
    title: "Curtain of the Feral Chart",
    summary: "A local guide breaks the rules and pays in memories.",
    moral: "Curiosity without compassion sharpens the claws of the dark.",
    story: "In an illegal surgery den, a bakeneko named Hibi prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that anyone who films the haunt records only their own confession. Since the tale spread, Children dare each other to knock only once.",
    keywords: ["esquecimento", "den", "curtain", "bakeneko"],
  },
  {
    id: "bakeneko-061",
    theme: "hospital",
    title: "File of Residual Static",
    summary: "A bakeneko invites mortals to test a boundary they should respect.",
    moral: "Fear thrives when arrogance silences warnings.",
    story: "In the shuttered hospital wing, a bakeneko named Nami prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that those who ignore the omen wake up marked with charcoal paw prints. Since the tale spread, now commuters hang cat charms on emergency cords.",
    keywords: ["hospital", "wing", "file", "bakeneko"],
  },
  {
    id: "bakeneko-062",
    theme: "maldicao",
    title: "Room of the Flooded Ward",
    summary: "A haunted site trades sanctuary for uncomfortable truth.",
    moral: "Curses bloom wherever pride refuses to kneel.",
    story: "In an empty theme park, a bakeneko named Kage prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that the guilty hear their secrets counted each midnight. Since the tale spread, Caretakers chalk paw prints near the fuse box.",
    keywords: ["maldicao", "park", "room", "bakeneko"],
  },
  {
    id: "bakeneko-063",
    theme: "fantasma",
    title: "Whisper of the Third Shift",
    summary: "A rumor grows teeth when ignored by those in power.",
    moral: "Every forgotten victim eventually drafts their own rescue.",
    story: "In the coal furnace tunnels, a bakeneko named En prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that any patient file removed grows teeth and returns. Since the tale spread, Graffiti artists sketch twin tails on every exit sign.",
    keywords: ["fantasma", "tunnels", "whisper", "bakeneko"],
  },
  {
    id: "bakeneko-064",
    theme: "vinganca",
    title: "Ward of the Returned Gaze",
    summary: "A caretaker learns why apologies are more precious than locks.",
    moral: "The dead wait patiently for a listening ear.",
    story: "In a clockwork museum, a bakeneko named Toki prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that any who run are chased by echoes wearing their shoes. Since the tale spread, Paramedics leave bowls of cream by the loading bay.",
    keywords: ["vinganca", "museum", "ward", "bakeneko"],
  },
  {
    id: "bakeneko-065",
    theme: "pesadelo",
    title: "Wing of the Endless Intake",
    summary: "A traveling skeptic discovers that curiosity feeds the dark.",
    moral: "Justice from the shadows collects double interest.",
    story: "In the locked records vault, a bakeneko named Sumi prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that visitors who mock the place lose their shadow. Since the tale spread, Visitors count every window twice before leaving.",
    keywords: ["pesadelo", "vault", "wing", "bakeneko"],
  },
  {
    id: "bakeneko-066",
    theme: "yokai",
    title: "Ledger of Lamented Check Out",
    summary: "A family secret crawls back through abandoned corridors.",
    moral: "Those who barter with grief must carry the change.",
    story: "In a derelict observatory, a bakeneko named Rai prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that trespassers become silhouettes on the wall until dawn. Since the tale spread, Security guards wear bells hidden inside sleeves.",
    keywords: ["yokai", "observatory", "ledger", "bakeneko"],
  },
  {
    id: "bakeneko-067",
    theme: "memoria",
    title: "Night of Needle Weather",
    summary: "A midnight crew bargains with a cat that remembers debts.",
    moral: "Silence can shield or strangle depending on who holds it.",
    story: "In the storm-buried library, a bakeneko named Kiri prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that resigned victims find ticket stubs stapled to their skin. Since the tale spread, Nurses whisper headcounts before passing doorways.",
    keywords: ["memoria", "library", "night", "bakeneko"],
  },
  {
    id: "bakeneko-068",
    theme: "obsessao",
    title: "Case of Mewling Silence",
    summary: "A ritual promises safety but demands payment in whispers.",
    moral: "Secrets rot faster than wounds.",
    story: "In a sunken freight dock, a bakeneko named Tsuru prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that anyone who speaks too loudly bites their tongue until it bleeds. Since the tale spread, Locals warn newcomers to applaud the unseen performer.",
    keywords: ["obsessao", "dock", "case", "bakeneko"],
  },
  {
    id: "bakeneko-069",
    theme: "ritual",
    title: "Altar of Lurking Consent",
    summary: "A collector of evidence meets the source of the stains.",
    moral: "Nightmares feast on promises never honored.",
    story: "In the plague quarantine garden, a bakeneko named Mizu prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that stubborn listeners find their reflections refusing to return. Since the tale spread, Night shift workers trade matches etched with whiskers.",
    keywords: ["ritual", "garden", "altar", "bakeneko"],
  },
  {
    id: "bakeneko-070",
    theme: "esquecimento",
    title: "Mask of the Velvet Sutra",
    summary: "A local guide breaks the rules and pays in memories.",
    moral: "Curiosity without compassion sharpens the claws of the dark.",
    story: "In a forgotten coastal fortress, a bakeneko named Neru prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that flashlights fail within three breaths of arrogance. Since the tale spread, Children dare each other to knock only once.",
    keywords: ["esquecimento", "fortress", "mask", "bakeneko"],
  },
  {
    id: "bakeneko-071",
    theme: "hospital",
    title: "Mirror of Sixteenth Bell",
    summary: "A bakeneko invites mortals to test a boundary they should respect.",
    moral: "Fear thrives when arrogance silences warnings.",
    story: "In the paper lantern warehouse, a bakeneko named Shiba prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that the emergency exit counts down names instead of seconds. Since the tale spread, now commuters hang cat charms on emergency cords.",
    keywords: ["hospital", "warehouse", "mirror", "bakeneko"],
  },
  {
    id: "bakeneko-072",
    theme: "maldicao",
    title: "Signal of the Hollow Surgeon",
    summary: "A haunted site trades sanctuary for uncomfortable truth.",
    moral: "Curses bloom wherever pride refuses to kneel.",
    story: "In an echoing radio tower, a bakeneko named Tohru prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that apprentice exorcists must replace a bulb with their own memory. Since the tale spread, Caretakers chalk paw prints near the fuse box.",
    keywords: ["maldicao", "tower", "signal", "bakeneko"],
  },
  {
    id: "bakeneko-073",
    theme: "fantasma",
    title: "Suture of the Paper Scalpel",
    summary: "A rumor grows teeth when ignored by those in power.",
    moral: "Every forgotten victim eventually drafts their own rescue.",
    story: "In the rusted aquarium, a bakeneko named Kuzu prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that living guests sneeze out saltwater moss for a week. Since the tale spread, Graffiti artists sketch twin tails on every exit sign.",
    keywords: ["fantasma", "aquarium", "suture", "bakeneko"],
  },
  {
    id: "bakeneko-074",
    theme: "vinganca",
    title: "Threshold of the Bone Lantern",
    summary: "A caretaker learns why apologies are more precious than locks.",
    moral: "The dead wait patiently for a listening ear.",
    story: "In an abandoned bathhouse, a bakeneko named Kane prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that running water speaks in the voice of the last person ignored. Since the tale spread, Paramedics leave bowls of cream by the loading bay.",
    keywords: ["vinganca", "bathhouse", "threshold", "bakeneko"],
  },
  {
    id: "bakeneko-075",
    theme: "pesadelo",
    title: "Vial of the Phantom Siren",
    summary: "A traveling skeptic discovers that curiosity feeds the dark.",
    moral: "Justice from the shadows collects double interest.",
    story: "In the silent bell factory, a bakeneko named Azra prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that visitors leave with pockets full of rust they never collected. Since the tale spread, Visitors count every window twice before leaving.",
    keywords: ["pesadelo", "factory", "vial", "bakeneko"],
  },
  {
    id: "bakeneko-076",
    theme: "yokai",
    title: "Catwalk of Forgotten Vespers",
    summary: "A family secret crawls back through abandoned corridors.",
    moral: "Those who barter with grief must carry the change.",
    story: "In a collapsed textile mill, a bakeneko named Ino prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that every skeptic discovers a voice sealed inside their throat. Since the tale spread, Security guards wear bells hidden inside sleeves.",
    keywords: ["yokai", "mill", "catwalk", "bakeneko"],
  },
  {
    id: "bakeneko-077",
    theme: "memoria",
    title: "Bargain of the Withered Nurse",
    summary: "A midnight crew bargains with a cat that remembers debts.",
    moral: "Silence can shield or strangle depending on who holds it.",
    story: "In the night market basement, a bakeneko named Kori prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that apologies are the only currency accepted by the doors. Since the tale spread, Nurses whisper headcounts before passing doorways.",
    keywords: ["memoria", "basement", "bargain", "bakeneko"],
  },
  {
    id: "bakeneko-078",
    theme: "obsessao",
    title: "Pulse of Catcalled Promises",
    summary: "A ritual promises safety but demands payment in whispers.",
    moral: "Secrets rot faster than wounds.",
    story: "In an uprooted shrine, a bakeneko named Jiro prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that stair rails pulse like arteries around liars. Since the tale spread, Locals warn newcomers to applaud the unseen performer.",
    keywords: ["obsessao", "shrine", "pulse", "bakeneko"],
  },
  {
    id: "bakeneko-079",
    theme: "ritual",
    title: "Siren of the Static Choir",
    summary: "A collector of evidence meets the source of the stains.",
    moral: "Nightmares feast on promises never honored.",
    story: "In the provincial archive, a bakeneko named Mika prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that every question adds a crack to the nearest bone jar. Since the tale spread, Night shift workers trade matches etched with whiskers.",
    keywords: ["ritual", "archive", "siren", "bakeneko"],
  },
  {
    id: "bakeneko-080",
    theme: "esquecimento",
    title: "Curtain of the Feral Chart",
    summary: "A local guide breaks the rules and pays in memories.",
    moral: "Curiosity without compassion sharpens the claws of the dark.",
    story: "In an underground theater, a bakeneko named Nagi prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that anyone who films the haunt records only their own confession. Since the tale spread, Children dare each other to knock only once.",
    keywords: ["esquecimento", "theater", "curtain", "bakeneko"],
  },
  {
    id: "bakeneko-081",
    theme: "hospital",
    title: "File of Residual Static",
    summary: "A bakeneko invites mortals to test a boundary they should respect.",
    moral: "Fear thrives when arrogance silences warnings.",
    story: "In the back alley morgue, a bakeneko named Oba prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that those who ignore the omen wake up marked with charcoal paw prints. Since the tale spread, now commuters hang cat charms on emergency cords.",
    keywords: ["hospital", "morgue", "file", "bakeneko"],
  },
  {
    id: "bakeneko-082",
    theme: "maldicao",
    title: "Room of the Flooded Ward",
    summary: "A haunted site trades sanctuary for uncomfortable truth.",
    moral: "Curses bloom wherever pride refuses to kneel.",
    story: "In a drowned bell road, a bakeneko named Retsu prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that the guilty hear their secrets counted each midnight. Since the tale spread, Caretakers chalk paw prints near the fuse box.",
    keywords: ["maldicao", "road", "room", "bakeneko"],
  },
  {
    id: "bakeneko-083",
    theme: "fantasma",
    title: "Whisper of the Third Shift",
    summary: "A rumor grows teeth when ignored by those in power.",
    moral: "Every forgotten victim eventually drafts their own rescue.",
    story: "In the forest crematorium, a bakeneko named Sora prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that any patient file removed grows teeth and returns. Since the tale spread, Graffiti artists sketch twin tails on every exit sign.",
    keywords: ["fantasma", "crematorium", "whisper", "bakeneko"],
  },
  {
    id: "bakeneko-084",
    theme: "vinganca",
    title: "Ward of the Returned Gaze",
    summary: "A caretaker learns why apologies are more precious than locks.",
    moral: "The dead wait patiently for a listening ear.",
    story: "In a decommissioned lighthouse, a bakeneko named Tara prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that any who run are chased by echoes wearing their shoes. Since the tale spread, Paramedics leave bowls of cream by the loading bay.",
    keywords: ["vinganca", "lighthouse", "ward", "bakeneko"],
  },
  {
    id: "bakeneko-085",
    theme: "pesadelo",
    title: "Wing of the Endless Intake",
    summary: "A traveling skeptic discovers that curiosity feeds the dark.",
    moral: "Justice from the shadows collects double interest.",
    story: "In the midnight cable car, a bakeneko named Une prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that visitors who mock the place lose their shadow. Since the tale spread, Visitors count every window twice before leaving.",
    keywords: ["pesadelo", "car", "wing", "bakeneko"],
  },
  {
    id: "bakeneko-086",
    theme: "yokai",
    title: "Ledger of Lamented Check Out",
    summary: "A family secret crawls back through abandoned corridors.",
    moral: "Those who barter with grief must carry the change.",
    story: "In a sealed train carriage, a bakeneko named Yura prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that trespassers become silhouettes on the wall until dawn. Since the tale spread, Security guards wear bells hidden inside sleeves.",
    keywords: ["yokai", "carriage", "ledger", "bakeneko"],
  },
  {
    id: "bakeneko-087",
    theme: "memoria",
    title: "Night of Needle Weather",
    summary: "A midnight crew bargains with a cat that remembers debts.",
    moral: "Silence can shield or strangle depending on who holds it.",
    story: "In the flooded subway station, a bakeneko named Zei prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that resigned victims find ticket stubs stapled to their skin. Since the tale spread, Nurses whisper headcounts before passing doorways.",
    keywords: ["memoria", "station", "night", "bakeneko"],
  },
  {
    id: "bakeneko-088",
    theme: "obsessao",
    title: "Case of Mewling Silence",
    summary: "A ritual promises safety but demands payment in whispers.",
    moral: "Secrets rot faster than wounds.",
    story: "In a snowbound clinic, a bakeneko named Haku prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that anyone who speaks too loudly bites their tongue until it bleeds. Since the tale spread, Locals warn newcomers to applaud the unseen performer.",
    keywords: ["obsessao", "clinic", "case", "bakeneko"],
  },
  {
    id: "bakeneko-089",
    theme: "ritual",
    title: "Altar of Lurking Consent",
    summary: "A collector of evidence meets the source of the stains.",
    moral: "Nightmares feast on promises never honored.",
    story: "In the mirror lined dormitory, a bakeneko named Ire prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that stubborn listeners find their reflections refusing to return. Since the tale spread, Night shift workers trade matches etched with whiskers.",
    keywords: ["ritual", "dormitory", "altar", "bakeneko"],
  },
  {
    id: "bakeneko-090",
    theme: "esquecimento",
    title: "Mask of the Velvet Sutra",
    summary: "A local guide breaks the rules and pays in memories.",
    moral: "Curiosity without compassion sharpens the claws of the dark.",
    story: "In an illegal surgery den, a bakeneko named Kama prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that flashlights fail within three breaths of arrogance. Since the tale spread, Children dare each other to knock only once.",
    keywords: ["esquecimento", "den", "mask", "bakeneko"],
  },
  {
    id: "bakeneko-091",
    theme: "hospital",
    title: "Mirror of Sixteenth Bell",
    summary: "A bakeneko invites mortals to test a boundary they should respect.",
    moral: "Fear thrives when arrogance silences warnings.",
    story: "In the shuttered hospital wing, a bakeneko named Lune prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that the emergency exit counts down names instead of seconds. Since the tale spread, now commuters hang cat charms on emergency cords.",
    keywords: ["hospital", "wing", "mirror", "bakeneko"],
  },
  {
    id: "bakeneko-092",
    theme: "maldicao",
    title: "Signal of the Hollow Surgeon",
    summary: "A haunted site trades sanctuary for uncomfortable truth.",
    moral: "Curses bloom wherever pride refuses to kneel.",
    story: "In an empty theme park, a bakeneko named Mara prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that apprentice exorcists must replace a bulb with their own memory. Since the tale spread, Caretakers chalk paw prints near the fuse box.",
    keywords: ["maldicao", "park", "signal", "bakeneko"],
  },
  {
    id: "bakeneko-093",
    theme: "fantasma",
    title: "Suture of the Paper Scalpel",
    summary: "A rumor grows teeth when ignored by those in power.",
    moral: "Every forgotten victim eventually drafts their own rescue.",
    story: "In the coal furnace tunnels, a bakeneko named Nao prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that living guests sneeze out saltwater moss for a week. Since the tale spread, Graffiti artists sketch twin tails on every exit sign.",
    keywords: ["fantasma", "tunnels", "suture", "bakeneko"],
  },
  {
    id: "bakeneko-094",
    theme: "vinganca",
    title: "Threshold of the Bone Lantern",
    summary: "A caretaker learns why apologies are more precious than locks.",
    moral: "The dead wait patiently for a listening ear.",
    story: "In a clockwork museum, a bakeneko named Ori prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that running water speaks in the voice of the last person ignored. Since the tale spread, Paramedics leave bowls of cream by the loading bay.",
    keywords: ["vinganca", "museum", "threshold", "bakeneko"],
  },
  {
    id: "bakeneko-095",
    theme: "pesadelo",
    title: "Vial of the Phantom Siren",
    summary: "A traveling skeptic discovers that curiosity feeds the dark.",
    moral: "Justice from the shadows collects double interest.",
    story: "In the locked records vault, a bakeneko named Peko prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that visitors leave with pockets full of rust they never collected. Since the tale spread, Visitors count every window twice before leaving.",
    keywords: ["pesadelo", "vault", "vial", "bakeneko"],
  },
  {
    id: "bakeneko-096",
    theme: "yokai",
    title: "Catwalk of Forgotten Vespers",
    summary: "A family secret crawls back through abandoned corridors.",
    moral: "Those who barter with grief must carry the change.",
    story: "In a derelict observatory, a bakeneko named Quen prowls among bleeding walls. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that every skeptic discovers a voice sealed inside their throat. Since the tale spread, Security guards wear bells hidden inside sleeves.",
    keywords: ["yokai", "observatory", "catwalk", "bakeneko"],
  },
  {
    id: "bakeneko-097",
    theme: "memoria",
    title: "Bargain of the Withered Nurse",
    summary: "A midnight crew bargains with a cat that remembers debts.",
    moral: "Silence can shield or strangle depending on who holds it.",
    story: "In the storm-buried library, a bakeneko named Risa prowls among veins painted inside wallpaper. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that apologies are the only currency accepted by the doors. Since the tale spread, Nurses whisper headcounts before passing doorways.",
    keywords: ["memoria", "library", "bargain", "bakeneko"],
  },
  {
    id: "bakeneko-098",
    theme: "obsessao",
    title: "Pulse of Catcalled Promises",
    summary: "A ritual promises safety but demands payment in whispers.",
    moral: "Secrets rot faster than wounds.",
    story: "In a sunken freight dock, a bakeneko named Sei prowls among elevators stopping between seconds. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that stair rails pulse like arteries around liars. Since the tale spread, Locals warn newcomers to applaud the unseen performer.",
    keywords: ["obsessao", "dock", "pulse", "bakeneko"],
  },
  {
    id: "bakeneko-099",
    theme: "ritual",
    title: "Siren of the Static Choir",
    summary: "A collector of evidence meets the source of the stains.",
    moral: "Nightmares feast on promises never honored.",
    story: "In the plague quarantine garden, a bakeneko named Tama prowls among candles that burn without flame. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that every question adds a crack to the nearest bone jar. Since the tale spread, Night shift workers trade matches etched with whiskers.",
    keywords: ["ritual", "garden", "siren", "bakeneko"],
  },
  {
    id: "bakeneko-100",
    theme: "esquecimento",
    title: "Curtain of the Feral Chart",
    summary: "A local guide breaks the rules and pays in memories.",
    moral: "Curiosity without compassion sharpens the claws of the dark.",
    story: "In a forgotten coastal fortress, a bakeneko named Ume prowls among nurse call buttons screaming. The cat collects secrets whispered by intruders and trades them for temporary passage. Those who bargain without humility learn that anyone who films the haunt records only their own confession. Since the tale spread, Children dare each other to knock only once.",
    keywords: ["esquecimento", "fortress", "curtain", "bakeneko"],
  }
]

